### ISSUE TITLE
chromium-browser does not work on Google sites

### ISSUE THREAD

**Issue by kaplas** [futurice/chilipie-kiosk#9] opened 2016-06-02 09:18 UTC
Google sites, such as Google Analytics dashboards, do not work with the version of `chromium-browser` currently installed. Attempts to access those pages give the famous `_ERR_SSL_PROTOCOL_ERROR_` and the `--ignore-certificate-errors` command line flag does not affect the situation.

According to [an answer at askubuntu.com](http://askubuntu.com/a/737053) this issue manifested in some particular versions of `chromium-browser` package, and have since been fixed. So an update to the package would be needed here. However, I heard from @jareware that more current version of Chromium segfaults on the image at the moment, so there might be even more work required to fix this issue than what it looks like.

**Comment by kimmobrunfeldt** [comment] 2016-08-31 10:07
I think we are running into this same issue, have you checked: https://www.raspberrypi.org/forums/viewtopic.php?t=72587&p=522851

So could it be caused by:

* Incorrect time in the system
* Not having the latest certificates installed

**Comment by kimmobrunfeldt** [comment] 2016-08-31 10:21
I tried both of those suggestions but they didn't help. Also other sites, such as facebook.com give us `ERR_SSL_PROTOCOL_ERROR`.

**Comment by jareware** [comment] 2016-09-04 09:50
This has been addressed in af98f4b9b0fd9736fd36a3aa3ad4f4a26ec8368b, which will be included in the `v1.2` image, which is going into pre-release testing next week.

Thanks for contributing! ❤️

**Comment by jareware** [comment] 2016-09-10 11:46
Released in `v1.2`.

**Closed** 2016-09-10 11:47 UTC
